min_frd_rating: 0.75
domains:
    - nytimes.com
    - theatlantic.com
diffbot_batch_size: 50
bucket: ai.summer.1mwords.test
region: us-east-1
save_messages: true
local_s3: local_bucket
local_s3_results: local_result_bucket
ec2_ip: 52.91.194.132
lambda_function_name: WordTask
duckduckgo_sources:  # Acceptable sources for DuckDuckGo's instant answer API
    - Wikipedia
    - wiktionary
    - Star Wars Fanon Wiki  # May the dictionary be with you.
    - Abbreviations.com
    - Jargon
remove_messages: true
save_html: false
