min_frd_rating: 0.75
min_frd_prob: 0.75
domains:
    - nytimes.com
    - theatlantic.com
diffbot_batch_size: 50
bucket: ai.summer.serapis.messages
result_bucket: ai.summer.serapis.results
region: us-east-1
model_zip_name: model.zip
model_s3_bucket: summer.1m.frd-models
save_messages: true
local_s3: local_bucket
log_to_file: false
local_s3_results: local_result_bucket
ec2_ip: 52.91.194.132
google_cse: 000579440470800426354:_4qo2s0ijsi  # borrowed from the pattern library
lambda_function_name: WordTask
search_engine: bing  # use google or bing here
request_seconds_before_retry: 8
request_retry: 3
add_word_interval: 0 # seconds to wait before adding words from a wordlist
duckduckgo_sources:  # Acceptable sources for DuckDuckGo's instant answer API
    - Wikipedia
    - wiktionary
    - Star Wars Fanon Wiki  # May the dictionary be with you.
    - Abbreviations.com
    - Jargon
remove_messages: true
save_html: false
exclude_domains:
    - youtube.com
    - wikipedia.org
    - amazon.com
    - airbnb.com
    - wordnik.com
    - twitter.com
    - instagram.com
nltk_corpora:
    - punkt
    - averaged_perceptron_tagger
    
