min_frd_prob: 0.5
min_frd_rating: 0.0
save_messages: false
add_word_interval: 10
remove_messages: false
save_html: false
log_to_file: true
es_host: search-wordnik-dev-es-grlfahewx54ezx4al4d4642c7q.us-west-1.es.amazonaws.com
