search:
 -
   url: http://everydayfeminism.com/2015/08/4-tired-tropes-misogynoir
   domain: everydayfeminism.com
   date: 2015-08-03
   title: 4 Tired Tropes That Perfectly Explain What Misogynoir Is ...
   summary: "Misogynoir – a portmanteau that combines “misogyny” and the French word for black, “noir” – is a term coined by the queer Black feminist Moy"
 -
   url: https://en.wikipedia.org/wiki/Misogynoir
   domain: wikipedia.org
   date: 2015-11-03
   title: "Misogynoir - Wikipedia, the free encyclopedia"
   summary: "Misogynoir is a term referring to misogyny directed towards Black women, where race and gender both play roles in bias. It was coined by queer Black feminist ..."
 -
   url: http://www.theguardian.com/lifeandstyle/2015/oct/05/what-is-misogynoir
   domain: theguardian.com
   date: 2015-10-05
   title: "Misogynoir: where racism and sexism meet - The Guardian"
   summary: "“Misogynoir provides a racialised nuance that mainstream feminism wasn't catching,” says black feminist commentator, Feminista Jones."




parser:
   "https://en.wikipedia.org/wiki/Misogynoir":
      author: 'Wikipedia'
      body: '''Misogynoir is a term referring to misogyny directed towards Black women, where race and gender both play roles in bias. It was coined by queer Black feminist scholar Moya Bailey, who created the term to address misogyny directed toward black women in American visual and popular culture. Trudy of Gradient Lair, a womanist blog about Black women and art, media, social media, socio-politics and culture, has also been credited in developing the lexical definition of the term.'''
   "http://www.theguardian.com/lifeandstyle/2015/oct/05/what-is-misogynoir":
      author: 'Eliza Anyangwe'
      body: '''
But what is alleged to have happened at Dstrkt isn’t just about race; the accused promoter is black. It’s about gender too. Discrimination, prejudice and unchecked fear aimed specifically at black women now has a name: misogynoir.
The term was coined in 2010 by gay black feminist American academic Moya Bailey, who defined it “to describe the particular brand of hatred directed at black women in American visual and popular culture”.
Since then black women – and some men – predominantly on social media, have taken ownership of the term, using it to describe prejudice experienced in a range of contexts.
“Misogynoir provides a racialised nuance that mainstream feminism wasn’t catching,” says black feminist commentator, Feminista Jones. “We are talking about misogyny, yes, but there is a specific misogyny that is aimed at black women and is uniquely detrimental to black women.”
      '''
   "http://everydayfeminism.com/2015/08/4-tired-tropes-misogynoir":
      author: 'Kesiena Boom'
      body: '''
A few weeks ago, a white woman came up to me as I walked through my city’s queer district.
She leered at me, barked “You’re hot” in my face, and reached out and roughly grabbed my breast.
Now, this wasn’t the first time a stranger had touched my chest in public without my consent.  And so while I was hurt and disgusted, I wasn’t exactly massively surprised.
I shook the encounter off – feeling a little shaky and violated – and continued down the street.
All of two damn minutes passed before a white man came up close, looked me up and down, snapped his fingers in a “Z” formation and said, “Damn, girrrrlfriend! Work it! You look fierce.”
On this particular day, I was makeup free, clad in my omnipresent black Doc Martens boots, and dressed in baggy overalls that make me look like a plumber who just got off shift. There was nothing fierce about it.
My two non-Black female friends who stood next to me, however, did look fierce – dressed and made up to the nines and resplendent in high heels. Yet, they went on unnoticed.
If these accounts seem gross – but totally unfamiliar – to you then my guess is that you might be white.
Because whether cognizant of it or not, those two white strangers participated in and perpetuated the phenomenon of what we call misogynoir – the first by treating my body like a sexual plaything she was entitled to, and the second by projecting his stereotypical and narrow view of Black womanhood onto me.
Misogynoir – a portmanteau that combines “misogyny” and the French word for black, “noir” – is a term coined by the queer Black feminist Moya Bailey to describe the particular racialized sexism that Black women face.
It’s a word used to acknowledge the very specific convergence of anti-Blackness and misogyny, and therefore is not applicable to non-Black women of color (or white women).
And it’s often overlooked in feminist discourse – because it disrupts the tendency that mainstream feminism has of universalizing womanhood as a uniformly shared experience based on the default narrative of white women.  
Insisting that conversations around misogyny disregard race or take a “colorblind” approach are misguided and wrong-footed. Because only by accurately naming the nuances of oppressive behavior can we understand their origins and equip ourselves with the tools to bring them down.
That’s why discussing, recognizing, and understanding misogynoir is crucial to an effective and compassionate feminism.
So let’s start by understanding the following four tropes, pervasively woven into popular media, which contribute to making society a more hostile place for Black women.
      '''
